# Generated by Django 5.0.2 on 2025-02-19 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(default='', max_length=50)),
                ('rank', models.CharField(default='', max_length=50)),
                ('rarity', models.IntegerField(default=0)),
                ('defense', models.JSONField(default=dict)),
                ('resistances', models.JSONField(default=dict)),
                ('name', models.CharField(default='', max_length=50)),
                ('slots', models.JSONField(default=dict)),
                ('skills', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='simpleWeapons',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
