# Generated by Django 5.0.2 on 2025-02-19 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(default='', max_length=50)),
                ('rarity', models.IntegerField(default=0)),
                ('attack', models.JSONField(default=dict)),
                ('elderseal', models.CharField(default='', max_length=50)),
                ('attributes', models.JSONField(default=dict)),
                ('damageType', models.CharField(default='', max_length=50)),
                ('name', models.CharField(default='', max_length=50)),
                ('durability', models.JSONField(blank=True, default=dict, null=True)),
                ('slots', models.JSONField(default=dict)),
                ('elements', models.JSONField(default=dict)),
            ],
        ),
        migrations.DeleteModel(
            name='simpleWeapons',
        ),
    ]
