# Generated by Django 5.0.2 on 2025-04-15 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_weapon_delete_simpleweapons'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charm',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('ranks', models.JSONField(default=dict)),
            ],
        ),
        migrations.AddField(
            model_name='armor',
            name='setbonus',
            field=models.JSONField(default=dict),
        ),
    ]
