# Generated by Django 5.0.2 on 2025-04-23 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='ranks',
        ),
    ]
