# Generated by Django 5.0.2 on 2025-04-28 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_decoration_delete_skill_charm_slot'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotionValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weaponType', models.CharField(default='', max_length=50)),
                ('stun', models.IntegerField(default=0)),
                ('exhaust', models.IntegerField(default=0)),
                ('hits', models.JSONField(default=dict)),
                ('name', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
