# Generated by Django 5.0.2 on 2025-05-05 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_motionvalues'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MotionValues',
        ),
    ]
